const defaultOptions = {
    pupilColor: 'black',
    leftScleraColor: 'white',
    rightScleraColor: 'white',
    rightPupilColor: 'white',
    leftPupilColor: 'white',
    scleraColor: 'white',
    scleraOutlineWidth: 2,
    scleraOutlineColor: "#000",
    leftFrontPawColor: "yellow",
    leftFrontPawSize: "50px",
    rightFrontPawColor: "yellow",
    rightFrontPawSize: "50px",
    browRidgeWidth: "200px",
    browRidgeHeight: "90px",
    backgroundColor: 'black',
    catMargin: "auto",
    catWidth: '380px',
    leftEarHeight: "70px",
    clockFaceColor: 'rgb(255, 255, 255, 0.3)',
    secondHandPointColor: 'rgba(0, 0, 0, 0)',
    clockOutlineColor: 'black',
    secondHandColor: '#D40000',
    minuteHandColor: 'black',
    hourHandColor: 'black',
    minuteMarksColor: 'black',
    hourMarkColor: 'black',
    leftEarColor: 'yellow',
    rightEarColor: 'yellow',
    headColor: 'yellow',
    catColor: 'yellow',
  }